 
version: '3.8'

services:
  # Laravel Service
  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravel:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - laravel_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - laravel_network

  # MySQL Service
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  # Random HTTP Docker Image (Optional)
  random_http:
    image: nginx:alpine
    container_name: random-http
    profiles:
      - random
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  mysql_data:
